### ISSUE TITLE
macOS版が消えてる？

### ISSUE THREAD

**Issue by askdkc** [groonga/groonga-normalizer-mysql#28]
ReadMeにHomebrewを用いたmacOS版のインストール方法が載っているのですが、実際にインストールしようとするとエラーになります

## ReadMeのインストール方法
<img width="869" alt="image" src="https://github.com/groonga/groonga-normalizer-mysql/assets/7894265/1abce032-7f6d-4dfc-852f-72928dc73226">

## 実際のアウトプット
```bash
brew install groonga-normalizer-mysql

Warning: No available formula with the name "groonga-normalizer-mysql".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for groonga-normalizer-mysql.
```

**Comment by kou** [comment]
あぁ、`groonga` formulaに統合されたので個別にインストールする必要はなくなったんですよ。

`brew install groonga`にしないといけないですねぇ。

**Comment by askdkc** [comment]
@kou さん

なるほどですね！

ということでReadMe更新のPR出しました。

**Comment by askdkc** [comment]
@kou さん

ちなみにmacOSの`groonga`だとノーマライザーの`NormalizerMySQLUnicodeCIExceptKanaCIKanaWithVoicedSoundMark`を使えなかったりしますか？

```sql
testmysql=# create extension pgroonga;
CREATE EXTENSION

testmysql=# CREATE TABLE memos(id int, content text);
CREATE TABLE

testmysql=# CREATE INDEX pgroonga_content_index ON memos USING pgroonga(content) 
    WITH (normalizers = 'NormalizerMySQLUnicodeCIExceptKanaCIKanaWithVoicedSoundMark', 
          tokenizer = 'TokenMecab("use_reading", true)');

ERROR:  pgroonga: [option][normalizers][validate] invalid normalizers: 
<NormalizerMySQLUnicodeCIExceptKanaCIKanaWithVoicedSoundMark>: 
[info][set][normalizers][(anonymous)] failed to parse normalizers: 
<NormalizerMySQLUnicodeCIExceptKanaCIKanaWithVoicedSoundMark
```

**Comment by kou** [comment]
さすがです！

`WITH`の中に`plugins='normalizers/mysql`を書かないといけないんですよ。
https://pgroonga.github.io/ja/reference/create-index-using-pgroonga.html#custom-plugins
