### ISSUE TITLE
register fails on groonga-normalizer-mysql 1.0.7

### ISSUE THREAD

**Issue by fdiary** [groonga/groonga-normalizer-mysql#3]
I updated groonga (->5.0.0), groonga-normalizer-mysql (->1.0.7) and mroonga (->5.00) and found that MySQL normalizers were no longer available.

* 1.0.6
```
groonga > register normalizers/mysql
[[0,1423575108.6345,0.0283074378967285],true]

mroonga > SELECT mroonga_command('normalize NormalizerMySQLUnicodeCI Fauré');
+--------------------------------------------------------------+
| mroonga_command('normalize NormalizerMySQLUnicodeCI Fauré')  |
+--------------------------------------------------------------+
| {"normalized":"FAURE","types":[],"checks":[]}                |
+--------------------------------------------------------------+
```

* 1.0.7
```
groonga > register normalizers/mysql
[[-54,1423575036.73556,0.0113925933837891,"init func (grn_plugin_impl_init) not found, register func (grn_plugin_impl_register) not found and fin func (grn_plugin_impl_fi"],false]

mroonga > SELECT mroonga_command('normalize NormalizerMySQLUnicodeCI Fauré');
ERROR 1026 (HY000): [normalize] nonexistent normalizer: <NormalizerMySQLUnicodeCI>
```

For configure options, I only use '--disable-static'.

**Comment by kou** [comment]
Oh...

Did you use packages? Or did you build from sources?

**Comment by kou** [comment]
Could you try `groonga -n /tmp/db register normalizers/mysql`?

**Comment by fdiary** [comment]
I built it from source, with specifying groonga location by PKG_CONFIG_PATH.

And here is the output of `groonga -n /tmp/db register normalizers/mysql` (same as above)...
```
groonga -n /tmp/db register normalizers/mysql
[[-54,1423576555.42428,0.101418972015381,"init func (grn_plugin_impl_init) not found, register func (grn_plugin_impl_register) not found and fin func (grn_plugin_impl_fi"],false]
```

**Comment by kou** [comment]
Thanks! I can reproduce the problem.

We should confirm Travis CI before releasing: https://travis-ci.org/groonga/groonga-normalizer-mysql/builds/49991181

I'll release new version soon.

**Comment by fdiary** [comment]
Yes, now it's green. Thanks !!!

**Comment by kou** [comment]
Source has been uploaded: http://packages.groonga.org/source/groonga-normalizer-mysql/groonga-normalizer-mysql-1.0.8.tar.gz
Please use it!
