### ISSUE TITLE
Relase 1.2.2

### ISSUE THREAD

**Issue by komainu8** [groonga/groonga-normalizer-mysql#30]
- [x] リリースノート作成
- [x] パッケージのChange log更新
- [x] Ubuntu向けパッケージのビルド確認(nightly)
- [x] CI確認
- [x] タグ設定
- [x] ソースアーカイブアップロード
- [x] パッケージアップロード
- [x] バージョンの更新

**Comment by kou** [comment]
最初のタグはGitHub Releasesのアップロードがうまくいかなかった https://github.com/groonga/groonga-normalizer-mysql/actions/runs/6544720722 のでタグを削除して打ち直した。
https://github.com/groonga/groonga-normalizer-mysql/actions/runs/6567851617

ソースアーカイブは https://packages.groonga.org/source/groonga-normalizer-mysql/ ではなくてGitHub Releasesの方をプライマリーにした。
https://packages.groonga.org/source/groonga-normalizer-mysql/ の方にはリダイレクトを設定しているので今まで通りのルールのURLにアクセスしても引き続きダウンロードできる。
