### ISSUE TITLE
cannot find plugin file: </usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/normalizers/mysql.so>

### ISSUE THREAD

**Issue by s171063** [groonga/groonga-normalizer-mysql#4]
$ brew install --verbose --debug groonga

==> Downloading https://homebrew.bintray.com/bottles/groonga-5.0.9.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/groonga-5.0.9.yosemite.bottle.tar.gz
==> Verifying groonga-5.0.9.yosemite.bottle.tar.gz checksum
==> Pouring groonga-5.0.9.yosemite.bottle.tar.gz
tar xf /Library/Caches/Homebrew/groonga-5.0.9.yosemite.bottle.tar.gz
Changing install name in /usr/local/Cellar/groonga/5.0.9/bin/grndb
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/bin/grndb
  from @@HOMEBREW_PREFIX@@/opt/msgpack/lib/libmsgpack.4.dylib
    to /usr/local/opt/msgpack/lib/libmsgpack.4.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/bin/groonga
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/bin/groonga
  from @@HOMEBREW_PREFIX@@/opt/msgpack/lib/libmsgpack.4.dylib
    to /usr/local/opt/msgpack/lib/libmsgpack.4.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/bin/groonga-benchmark
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/bin/groonga-benchmark
  from @@HOMEBREW_PREFIX@@/opt/msgpack/lib/libmsgpack.4.dylib
    to /usr/local/opt/msgpack/lib/libmsgpack.4.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/bin/groonga-suggest-create-dataset
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/bin/groonga-suggest-create-dataset
  from @@HOMEBREW_PREFIX@@/opt/msgpack/lib/libmsgpack.4.dylib
    to /usr/local/opt/msgpack/lib/libmsgpack.4.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/functions/vector.so
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/query_expanders/tsv.so
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/ruby/eval.so
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/ruby/eval.so
  from @@HOMEBREW_PREFIX@@/opt/msgpack/lib/libmsgpack.4.dylib
    to /usr/local/opt/msgpack/lib/libmsgpack.4.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/ruby/load.so
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/ruby/load.so
  from @@HOMEBREW_PREFIX@@/opt/msgpack/lib/libmsgpack.4.dylib
    to /usr/local/opt/msgpack/lib/libmsgpack.4.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/suggest/suggest.so
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/suggest/suggest.so
  from @@HOMEBREW_PREFIX@@/opt/msgpack/lib/libmsgpack.4.dylib
    to /usr/local/opt/msgpack/lib/libmsgpack.4.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/table/table.so
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/table/table.so
  from @@HOMEBREW_PREFIX@@/opt/msgpack/lib/libmsgpack.4.dylib
    to /usr/local/opt/msgpack/lib/libmsgpack.4.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/groonga/plugins/token_filters/stop_word.so
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing dylib ID of /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
  from @@HOMEBREW_PREFIX@@/opt/groonga/lib/libgroonga.0.dylib
    to /usr/local/opt/groonga/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
  from @@HOMEBREW_PREFIX@@/opt/msgpack/lib/libmsgpack.4.dylib
    to /usr/local/opt/msgpack/lib/libmsgpack.4.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/sbin/groonga-httpd
  from @@HOMEBREW_CELLAR@@/groonga/5.0.9/lib/libgroonga.0.dylib
    to /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/sbin/groonga-httpd
  from @@HOMEBREW_PREFIX@@/opt/pcre/lib/libpcre.1.dylib
    to /usr/local/opt/pcre/lib/libpcre.1.dylib
Changing install name in /usr/local/Cellar/groonga/5.0.9/sbin/groonga-httpd
  from @@HOMEBREW_PREFIX@@/opt/openssl/lib/libcrypto.1.0.0.dylib
    to /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
==> Finishing up
ln -s ../../Cellar/groonga/5.0.9/etc/groonga/groonga.conf groonga.conf
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/fastcgi.conf fastcgi.conf
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/fastcgi.conf.default fastcgi.conf.default
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/fastcgi_params fastcgi_params
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/fastcgi_params.default fastcgi_params.default
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/groonga-httpd.conf groonga-httpd.conf
ln -s ../../../../Cellar/groonga/5.0.9/etc/groonga/httpd/html/50x.html 50x.html
ln -s ../../../../Cellar/groonga/5.0.9/etc/groonga/httpd/html/index.html index.html
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/koi-utf koi-utf
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/koi-win koi-win
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/mime.types mime.types
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/mime.types.default mime.types.default
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/nginx.conf.default nginx.conf.default
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/scgi_params scgi_params
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/scgi_params.default scgi_params.default
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/uwsgi_params uwsgi_params
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/uwsgi_params.default uwsgi_params.default
ln -s ../../../Cellar/groonga/5.0.9/etc/groonga/httpd/win-utf win-utf
ln -s ../../Cellar/groonga/5.0.9/etc/groonga/synonyms.tsv synonyms.tsv
ln -s ../Cellar/groonga/5.0.9/bin/grndb grndb
ln -s ../Cellar/groonga/5.0.9/bin/groonga groonga
ln -s ../Cellar/groonga/5.0.9/bin/groonga-benchmark groonga-benchmark
ln -s ../Cellar/groonga/5.0.9/bin/groonga-suggest-create-dataset groonga-suggest-create-dataset
ln -s ../Cellar/groonga/5.0.9/sbin/groonga-httpd groonga-httpd
ln -s ../Cellar/groonga/5.0.9/sbin/groonga-httpd-restart groonga-httpd-restart
ln -s ../Cellar/groonga/5.0.9/include/groonga groonga
ln -s ../../Cellar/groonga/5.0.9/share/doc/groonga groonga
ln -s ../Cellar/groonga/5.0.9/share/groonga groonga
ln -s ../../../../Cellar/groonga/5.0.9/share/man/ja/man1/groonga.1 groonga.1
ln -s ../../../Cellar/groonga/5.0.9/share/man/man1/groonga.1 groonga.1
ln -s ../Cellar/groonga/5.0.9/lib/groonga groonga
ln -s ../Cellar/groonga/5.0.9/lib/libgroonga.0.dylib libgroonga.0.dylib
ln -s ../Cellar/groonga/5.0.9/lib/libgroonga.a libgroonga.a
ln -s ../Cellar/groonga/5.0.9/lib/libgroonga.dylib libgroonga.dylib
ln -s ../../Cellar/groonga/5.0.9/lib/pkgconfig/groonga.pc groonga.pc
Changing dylib ID of /usr/local/Cellar/groonga/5.0.9/lib/libgroonga.0.dylib
  from /usr/local/opt/groonga/lib/libgroonga.0.dylib
    to /usr/local/opt/groonga/lib/libgroonga.0.dylib
==> Summary
🍺  /usr/local/Cellar/groonga/5.0.9: 1122 files, 29M

#########################################################
#########################################################

$ brew install --verbose --debug groonga-normalizer-mysql

==> Downloading https://homebrew.bintray.com/bottles/groonga-normalizer-mysql-1.1.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/groonga-normalizer-mysql-1.1.0.yosemite.bottle.tar.gz
==> Verifying groonga-normalizer-mysql-1.1.0.yosemite.bottle.tar.gz checksum
==> Pouring groonga-normalizer-mysql-1.1.0.yosemite.bottle.tar.gz
tar xf /Library/Caches/Homebrew/groonga-normalizer-mysql-1.1.0.yosemite.bottle.tar.gz
==> Finishing up
ln -s ../../Cellar/groonga-normalizer-mysql/1.1.0/share/doc/groonga-normalizer-mysql groonga-normalizer-mysql
ln -s ../../Cellar/groonga-normalizer-mysql/1.1.0/lib/pkgconfig/groonga-normalizer-mysql.pc groonga-normalizer-mysql.pc
==> Summary
🍺  /usr/local/Cellar/groonga-normalizer-mysql/1.1.0: 6 files, 72K

**Comment by kou** [comment]
Thanks!

Could you try `brew install --verbose --debug --build-from-source groonga-normalizer-mysql`?

**Comment by kou** [comment]
@cosmo0920 Could you try to include `mysql.so` into groonga-normalizer-mysql bottle? It seems that we can use PGroonga like approach for groonga-normalizer-mysql.

**Comment by cosmo0920** [comment]
I've found that `groonga-normalizer-mysql` formula build process causes another problem.
If he/she install with enabling sandbox feature, then installation failed:

```log
% brew install groonga-normalizer-mysql -v --sandbox
==> Using the sandbox
...
make[2]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/usr/local/Cellar/groonga/5.0.8/lib/groonga/plugins/normalizers'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   mysql.la '/usr/local/Cellar/groonga/5.0.8/lib/groonga/plugins/normalizers'
libtool: install: /usr/bin/install -c .libs/mysql.so /usr/local/Cellar/groonga/5.0.8/lib/groonga/plugins/normalizers/mysql.so
install: /usr/local/Cellar/groonga/5.0.8/lib/groonga/plugins/normalizers/mysql.so: Operation not permitted
make[2]: *** [install-normalizers_pluginsLTLIBRARIES] Error 71
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
==> Sandbox log
```

Because sandbox feature forbids to install another formula's Cellar directly.
Homebrew upstream CI build tasks always use sandbox feature.

**Comment by kou** [comment]
> I've found that groonga-normalizer-mysql formula build process causes another problem.

Could you also fix it?

**Comment by cosmo0920** [comment]
Perhaps, I could do it.

I've registered https://github.com/Homebrew/homebrew/pull/45889 to fix above two problems.

**Comment by s171063** [comment]
I finished install without error by trying <code>brew install --verbose --debug --build-from-source groonga-normalizer-mysql</code>.
Thank you for teaching.

**Comment by kou** [comment]
> I've registered Homebrew/homebrew#45889 to fix above two problems.

Great!

**Comment by kou** [comment]
> I finished install without error by trying `brew install --verbose --debug --build-from-source groonga-normalizer-mysql`.

Thanks for your report.
I close this ticket.
